name: Deploy to aapnel simlurah

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger aaPanel Webhook
        run: curl -s -L -k -X GET "${{ secrets.DEPLOY_WEBHOOK }}"
